/**
 * **Model** — the component library.
 *
 * GENERATED by `npm run footprints` from the KiCad footprints in `footprints/fab/`, which is the
 * vendored KiCad FabLib. Do not edit: drop a .kicad_mod in that directory, or change
 * `ocaml/footprints.ml`, and regenerate. Every file in the directory is emitted, so there is no list
 * here to fall out of step with what is on disk.
 *
 * The FabLib is 159 footprints and about a megabyte of pad outlines, which is four times the rest of
 * the app. Most of it is parts a rail cannot pass through — a forty-pin connector has no meaning
 * spliced into a run of copper tape — so this module holds only the ones that can be placed, and
 * `footprints.rest.generated.ts` holds the others for the palette to pull in on demand. That split is
 * a bundling decision and nothing more: whether a part can be placed is `placement()` in `parts.ts`,
 * which is asked about parts from both halves.
 *
 * A footprint is its pads, keyed by the pad name the part's own datasheet uses. Each pad carries its
 * outline as an SVG path about its own origin, where that origin sits in the part, which layers it
 * belongs to, and a drill if it is a hole. Coordinates are inches with y up — see `ocaml/kicad.ml`
 * for why, and `footprint.ts` for the helpers that read them.
 *
 * Whether a part can actually go in series on a rail is NOT recorded here. It is read off the pads by
 * `placement()` in `parts.ts`, which is the same reading `acrossPart` and `partFit` already do; a
 * second copy of that decision in generated data is a second copy to drift.
 */

/** A hole through the board, as opposed to a pad on it. */
export interface Drill {
  diameter: number;
  start: string;
  end: string;
  plated: boolean;
}

/** One terminal — or, with no copper layer, one mechanical hole. */
export interface Pad {
  /** The outline as an SVG path, inches, about this pad's own origin. */
  shape: string;
  /** Where that origin sits in the footprint, inches, y up. */
  pos: [number, number];
  layers: string[];
  /** The part's own pad number, 1-based. */
  index: number;
  drill?: Drill;
}

/** A part, as its pads. */
export type Footprint = Record<string, Pad>;

/** A library entry: the footprint plus what to call it. */
export interface Component {
  id: string;
  /** What the part is, in the words of its own footprint file's `descr` or `tags`. */
  note: string;
  footprint: Footprint;
}

/** Battery-Holder Coin-Cell CR2032 Linx BAT-HLD-001 — from `Battery-Holder_Coin-Cell_CR2032_Linx_BAT-HLD-001.kicad_mod`. */
export const BAT_COIN_20: Footprint = {
  "1": {
    shape: "M -0.049213 0.11811 L 0.049213 0.11811 L 0.049213 -0.11811 L -0.049213 -0.11811 L -0.049213 0.11811 ",
    pos: [-0.450787, 0],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 1,
  },
  "2": {
    shape: "M 0.350394 0 L 0.349643 0.022917 L 0.347396 0.045736 L 0.343661 0.068358 L 0.338454 0.090689 L 0.331798 0.11263 L 0.323722 0.13409 L 0.314259 0.154975 L 0.30345 0.175197 L 0.291342 0.194668 L 0.277986 0.213306 L 0.26344 0.231031 L 0.247766 0.247766 L 0.231031 0.26344 L 0.213306 0.277986 L 0.194668 0.291342 L 0.175197 0.30345 L 0.154975 0.314259 L 0.13409 0.323722 L 0.11263 0.331798 L 0.090689 0.338454 L 0.068358 0.343661 L 0.045736 0.347396 L 0.022917 0.349643 L 0 0.350394 L -0.022917 0.349643 L -0.045736 0.347396 L -0.068358 0.343661 L -0.090689 0.338454 L -0.11263 0.331798 L -0.13409 0.323722 L -0.154975 0.314259 L -0.175197 0.30345 L -0.194668 0.291342 L -0.213306 0.277986 L -0.231031 0.26344 L -0.247766 0.247766 L -0.26344 0.231031 L -0.277986 0.213306 L -0.291342 0.194668 L -0.30345 0.175197 L -0.314259 0.154975 L -0.323722 0.13409 L -0.331798 0.11263 L -0.338454 0.090689 L -0.343661 0.068358 L -0.347396 0.045736 L -0.349643 0.022917 L -0.350394 0 L -0.349643 -0.022917 L -0.347396 -0.045736 L -0.343661 -0.068358 L -0.338454 -0.090689 L -0.331798 -0.11263 L -0.323722 -0.13409 L -0.314259 -0.154975 L -0.30345 -0.175197 L -0.291342 -0.194668 L -0.277986 -0.213306 L -0.26344 -0.231031 L -0.247766 -0.247766 L -0.231031 -0.26344 L -0.213306 -0.277986 L -0.194668 -0.291342 L -0.175197 -0.30345 L -0.154975 -0.314259 L -0.13409 -0.323722 L -0.11263 -0.331798 L -0.090689 -0.338454 L -0.068358 -0.343661 L -0.045736 -0.347396 L -0.022917 -0.349643 L 0 -0.350394 L 0.022917 -0.349643 L 0.045736 -0.347396 L 0.068358 -0.343661 L 0.090689 -0.338454 L 0.11263 -0.331798 L 0.13409 -0.323722 L 0.154975 -0.314259 L 0.175197 -0.30345 L 0.194668 -0.291342 L 0.213306 -0.277986 L 0.231031 -0.26344 L 0.247766 -0.247766 L 0.26344 -0.231031 L 0.277986 -0.213306 L 0.291342 -0.194668 L 0.30345 -0.175197 L 0.314259 -0.154975 L 0.323722 -0.13409 L 0.331798 -0.11263 L 0.338454 -0.090689 L 0.343661 -0.068358 L 0.347396 -0.045736 L 0.349643 -0.022917 L 0.350394 0 ",
    pos: [0, 0],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 2,
  },
  "1_1": {
    shape: "M -0.049213 0.11811 L 0.049213 0.11811 L 0.049213 -0.11811 L -0.049213 -0.11811 L -0.049213 0.11811 ",
    pos: [0.450787, 0],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 3,
  },
};

/** BatteryContact Keystone 555 — from `BatteryContact_Keystone_555.kicad_mod`. */
export const BatteryContact_Keystone_555: Footprint = {
  "1": {
    shape: "M -0.07874 0.100394 L 0.07874 0.100394 L 0.07874 -0.100394 L -0.07874 -0.100394 L -0.07874 0.100394 ",
    pos: [-0.255906, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "1_1": {
    shape: "M -0.07874 0.046063 L 0.07874 0.046063 L 0.07874 -0.046063 L -0.07874 -0.046063 L -0.07874 0.046063 ",
    pos: [0.255906, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** SMD capacitor, aluminum electrolytic, Nichicon, 10.0x10.0mm — from `CP_Elec_100uF_Panasonic_EEE-FN1E101UL.kicad_mod`. */
export const CP_Elec_100uF_Panasonic_EEE_FN1E101UL: Footprint = {
  "1": {
    shape: "M -0.059055 0.019685 L 0.059055 0.019685 L 0.059055 -0.019685 L -0.059055 -0.019685 L -0.059055 0.019685 ",
    pos: [-0.102362, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.059055 0.019685 L 0.059055 0.019685 L 0.059055 -0.019685 L -0.059055 -0.019685 L -0.059055 0.019685 ",
    pos: [0.102362, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** CAP LITH HYBRID 10F 3.8V T/H — from `CP_Elec_10F_Tecate_TPLC-3R8.kicad_mod`. */
export const CP_Elec_10F_Tecate_TPLC_3R8: Footprint = {
  "1": {
    shape: "M 0.023622 0 L 0.02303 0.005256 L 0.021283 0.010249 L 0.018468 0.014728 L 0.014728 0.018468 L 0.010249 0.021283 L 0.005256 0.02303 L 0 0.023622 L -0.005256 0.02303 L -0.010249 0.021283 L -0.014728 0.018468 L -0.018468 0.014728 L -0.021283 0.010249 L -0.02303 0.005256 L -0.023622 0 L -0.02303 -0.005256 L -0.021283 -0.010249 L -0.018468 -0.014728 L -0.014728 -0.018468 L -0.010249 -0.021283 L -0.005256 -0.02303 L 0 -0.023622 L 0.005256 -0.02303 L 0.010249 -0.021283 L 0.014728 -0.018468 L 0.018468 -0.014728 L 0.021283 -0.010249 L 0.02303 -0.005256 L 0.023622 0 ",
    pos: [-0.068898, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.031496, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M 0.023622 0 L 0.02303 0.005256 L 0.021283 0.010249 L 0.018468 0.014728 L 0.014728 0.018468 L 0.010249 0.021283 L 0.005256 0.02303 L 0 0.023622 L -0.005256 0.02303 L -0.010249 0.021283 L -0.014728 0.018468 L -0.018468 0.014728 L -0.021283 0.010249 L -0.02303 0.005256 L -0.023622 0 L -0.02303 -0.005256 L -0.021283 -0.010249 L -0.018468 -0.014728 L -0.014728 -0.018468 L -0.010249 -0.021283 L -0.005256 -0.02303 L 0 -0.023622 L 0.005256 -0.02303 L 0.010249 -0.021283 L 0.014728 -0.018468 L 0.018468 -0.014728 L 0.021283 -0.010249 L 0.02303 -0.005256 L 0.023622 0 ",
    pos: [0.068898, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.031496, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** CP Elec 47uF Panasonic EEE-FN1H470XL — from `CP_Elec_47uF_Panasonic_EEE-FN1H470XL.kicad_mod`. */
export const CP_Elec_47uF_Panasonic_EEE_FN1H470XL: Footprint = {
  "1": {
    shape: "M -0.059055 0.019685 L 0.059055 0.019685 L 0.059055 -0.019685 L -0.059055 -0.019685 L -0.059055 0.019685 ",
    pos: [-0.102362, 0],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 1,
  },
  "2": {
    shape: "M -0.059055 0.019685 L 0.059055 0.019685 L 0.059055 -0.019685 L -0.059055 -0.019685 L -0.059055 0.019685 ",
    pos: [0.102362, 0],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 2,
  },
};

/** Capacitor SMD 0603 — from `C_0603.kicad_mod`. */
export const C_0603: Footprint = {
  "1": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [-0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Capacitor SMD 1206, hand soldering — from `C_1206.kicad_mod`. */
export const C_1206: Footprint = {
  "1": {
    shape: "M -0.023622 0.031496 L 0.023622 0.031496 L 0.023622 -0.031496 L -0.023622 -0.031496 L -0.023622 0.031496 ",
    pos: [-0.059055, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.023622 0.031496 L 0.023622 0.031496 L 0.023622 -0.031496 L -0.023622 -0.031496 L -0.023622 0.031496 ",
    pos: [0.059055, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** 20MHz ±50ppm Crystal 8pF 70 Ohms 2-SMD, No Lead — from `Crystal_NX5032GA-20.kicad_mod`. */
export const Crystal_NX5032GA_20: Footprint = {
  "1": {
    shape: "M -0.03937 0.047244 L 0.03937 0.047244 L 0.03937 -0.047244 L -0.03937 -0.047244 L -0.03937 0.047244 ",
    pos: [-0.07874, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.047244 L 0.03937 0.047244 L 0.03937 -0.047244 L -0.03937 -0.047244 L -0.03937 0.047244 ",
    pos: [0.07874, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Diode Schottky 0603 — from `Diode_Schottky_0603.kicad_mod`. */
export const Diode_Schottky_0603: Footprint = {
  "1": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [-0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Mini-SMA Schottky diode footprint — from `Diode_Schottky_MiniSMA.kicad_mod`. */
export const Diode_Schottky_MiniSMA: Footprint = {
  "1": {
    shape: "M -0.027559 0.037402 L 0.027559 0.037402 L 0.027559 -0.037402 L -0.027559 -0.037402 L -0.027559 0.037402 ",
    pos: [-0.064961, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.027559 0.037402 L 0.027559 0.037402 L 0.027559 -0.037402 L -0.027559 -0.037402 L -0.027559 0.037402 ",
    pos: [0.064961, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** SOD-123 footprint for the Schottky diode — from `Diode_Schottky_SOD123.kicad_mod`. */
export const Diode_Schottky_SOD123: Footprint = {
  "1": {
    shape: "M -0.019094 0.012795 L 0.019094 0.012795 L 0.019094 -0.012795 L -0.019094 -0.012795 L -0.019094 0.012795 ",
    pos: [-0.074803, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.019094 0.012795 L 0.019094 0.012795 L 0.019094 -0.012795 L -0.019094 -0.012795 L -0.019094 0.012795 ",
    pos: [0.074803, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** SMD Resomator/Filter Murata SFECV, 6.9x2.9mm^2 package — from `ECS-CR2-20.kicad_mod`. */
export const ECS_CR2_20: Footprint = {
  "1": {
    shape: "M -0.01378 0.080709 L 0.01378 0.080709 L 0.01378 -0.080709 L -0.01378 -0.080709 L -0.01378 0.080709 ",
    pos: [-0.059055, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.019685 0.080709 L 0.019685 0.080709 L 0.019685 -0.080709 L -0.019685 -0.080709 L -0.019685 0.080709 ",
    pos: [0, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.01378 0.080709 L 0.01378 0.080709 L 0.01378 -0.080709 L -0.01378 -0.080709 L -0.01378 0.080709 ",
    pos: [0.059055, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** Header JST PH 1x02 P2mm Vertical SMD — from `Header_JST_PH_1x02_P2mm_Vertical_SMD.kicad_mod`. */
export const Header_JST_PH_1x02_P2mm_Vertical_SMD: Footprint = {
  "1": {
    shape: "M -0.112205 0.023622 L 0.112205 0.023622 L 0.112205 -0.023622 L -0.112205 -0.023622 L -0.112205 0.023622 ",
    pos: [0, 0.03937],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.112205 0.023622 L 0.112205 0.023622 L 0.112205 -0.023622 L -0.112205 -0.023622 L -0.112205 0.023622 ",
    pos: [0, -0.03937],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "": {
    shape: "M -0.062992 0.035433 L 0.062992 0.035433 L 0.062992 -0.035433 L -0.062992 -0.035433 L -0.062992 0.035433 ",
    pos: [-0.07874, 0.133858],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
  "_1": {
    shape: "M -0.062992 0.035433 L 0.062992 0.035433 L 0.062992 -0.035433 L -0.062992 -0.035433 L -0.062992 0.035433 ",
    pos: [-0.07874, -0.133858],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 4,
  },
};

/** Header JST PH 1x03 P2mm Vertical SMD — from `Header_JST_PH_1x03_P2mm_Vertical_SMD.kicad_mod`. */
export const Header_JST_PH_1x03_P2mm_Vertical_SMD: Footprint = {
  "1": {
    shape: "M -0.112205 0.023622 L 0.112205 0.023622 L 0.112205 -0.023622 L -0.112205 -0.023622 L -0.112205 0.023622 ",
    pos: [0, 0.03937],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.112205 0.023622 L 0.112205 0.023622 L 0.112205 -0.023622 L -0.112205 -0.023622 L -0.112205 0.023622 ",
    pos: [0, -0.03937],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.112205 0.023622 L 0.112205 0.023622 L 0.112205 -0.023622 L -0.112205 -0.023622 L -0.112205 0.023622 ",
    pos: [0, -0.11811],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
  "": {
    shape: "M -0.062992 0.035433 L 0.062992 0.035433 L 0.062992 -0.035433 L -0.062992 -0.035433 L -0.062992 0.035433 ",
    pos: [-0.07874, 0.133858],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 4,
  },
  "_1": {
    shape: "M -0.062992 0.035433 L 0.062992 0.035433 L 0.062992 -0.035433 L -0.062992 -0.035433 L -0.062992 0.035433 ",
    pos: [-0.07874, -0.212598],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 5,
  },
};

/** Jumper, based on SMD 1206 resistor — from `Jumper_1206.kicad_mod`. */
export const Jumper_1206: Footprint = {
  "1": {
    shape: "M -0.027559 0.033465 L 0.027559 0.033465 L 0.027559 -0.033465 L -0.027559 -0.033465 L -0.027559 0.033465 ",
    pos: [-0.066929, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.027559 0.033465 L 0.027559 0.033465 L 0.027559 -0.033465 L -0.027559 -0.033465 L -0.027559 0.033465 ",
    pos: [0.066929, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** LED SMD 0603, hand soldering — from `LED_0603.kicad_mod`. */
export const LED_0603: Footprint = {
  "1": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [-0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** LED SMD 1206, hand soldering — from `LED_1206.kicad_mod`. */
export const LED_1206: Footprint = {
  "1": {
    shape: "M -0.027559 0.033465 L 0.027559 0.033465 L 0.027559 -0.033465 L -0.027559 -0.033465 L -0.027559 0.033465 ",
    pos: [-0.066929, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.027559 0.033465 L 0.027559 0.033465 L 0.027559 -0.033465 L -0.027559 -0.033465 L -0.027559 0.033465 ",
    pos: [0.066929, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** LED Luminus 1206 — from `LED_Luminus_1206.kicad_mod`. */
export const LED_Luminus_1206: Footprint = {
  "1": {
    shape: "M -0.045276 0.019685 L 0.045276 0.019685 L 0.045276 -0.019685 L -0.045276 -0.019685 L -0.045276 0.019685 ",
    pos: [0.037402, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.021654 0.027559 L 0.021654 0.027559 L 0.021654 -0.027559 L -0.021654 -0.027559 L -0.021654 0.027559 ",
    pos: [-0.055118, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Inductor SMD 1210, hand soldering — from `L_1210.kicad_mod`. */
export const L_1210: Footprint = {
  "1": {
    shape: "M -0.03937 0.049213 L 0.03937 0.049213 L 0.03937 -0.049213 L -0.03937 -0.049213 L -0.03937 0.049213 ",
    pos: [-0.07874, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.049213 L 0.03937 0.049213 L 0.03937 -0.049213 L -0.03937 -0.049213 L -0.03937 0.049213 ",
    pos: [0.07874, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** horizontal pin header SMD 2.54mm — from `PinHeader_01x02_P2.54mm_Horizontal_SMD.kicad_mod`. */
export const PinHeader_01x02_P2_54mm_Horizontal_SMD: Footprint = {
  "1": {
    shape: "M -0.049213 0.033465 L 0.049213 0.033465 L 0.049213 -0.033465 L -0.049213 -0.033465 L -0.049213 0.033465 ",
    pos: [0, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.049213 0.033465 L 0.049213 0.033465 L 0.049213 -0.033465 L -0.049213 -0.033465 L -0.049213 0.033465 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Through hole straight pin header, 2.54mm pitch, single row — from `PinHeader_01x02_P2.54mm_Vertical_THT_D1.4mm.kicad_mod`. */
export const PinHeader_01x02_P2_54mm_Vertical_THT_D1_4mm: Footprint = {
  "1": {
    shape: "M 0.041339 0 L 0.040711 0.007178 L 0.038846 0.014139 L 0.0358 0.020669 L 0.031667 0.026572 L 0.026572 0.031667 L 0.020669 0.0358 L 0.014139 0.038846 L 0.007178 0.040711 L 0 0.041339 L -0.007178 0.040711 L -0.014139 0.038846 L -0.020669 0.0358 L -0.026572 0.031667 L -0.031667 0.026572 L -0.0358 0.020669 L -0.038846 0.014139 L -0.040711 0.007178 L -0.041339 0 L -0.040711 -0.007178 L -0.038846 -0.014139 L -0.0358 -0.020669 L -0.031667 -0.026572 L -0.026572 -0.031667 L -0.020669 -0.0358 L -0.014139 -0.038846 L -0.007178 -0.040711 L 0 -0.041339 L 0.007178 -0.040711 L 0.014139 -0.038846 L 0.020669 -0.0358 L 0.026572 -0.031667 L 0.031667 -0.026572 L 0.0358 -0.020669 L 0.038846 -0.014139 L 0.040711 -0.007178 L 0.041339 0 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M 0.041339 0 L 0.040711 0.007178 L 0.038846 0.014139 L 0.0358 0.020669 L 0.031667 0.026572 L 0.026572 0.031667 L 0.020669 0.0358 L 0.014139 0.038846 L 0.007178 0.040711 L 0 0.041339 L -0.007178 0.040711 L -0.014139 0.038846 L -0.020669 0.0358 L -0.026572 0.031667 L -0.031667 0.026572 L -0.0358 0.020669 L -0.038846 0.014139 L -0.040711 0.007178 L -0.041339 0 L -0.040711 -0.007178 L -0.038846 -0.014139 L -0.0358 -0.020669 L -0.031667 -0.026572 L -0.026572 -0.031667 L -0.020669 -0.0358 L -0.014139 -0.038846 L -0.007178 -0.040711 L 0 -0.041339 L 0.007178 -0.040711 L 0.014139 -0.038846 L 0.020669 -0.0358 L 0.026572 -0.031667 L 0.031667 -0.026572 L 0.0358 -0.020669 L 0.038846 -0.014139 L 0.040711 -0.007178 L 0.041339 0 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** Through hole straight pin header, 2.54mm pitch, single row — from `PinHeader_01x02_P2.54mm_Vertical_THT_D1mm.kicad_mod`. */
export const PinHeader_01x02_P2_54mm_Vertical_THT_D1mm: Footprint = {
  "1": {
    shape: "M -0.033465 0 L -0.032822 -0.006529 L -0.030917 -0.012806 L -0.027825 -0.018592 L -0.023663 -0.023663 L -0.018592 -0.027825 L -0.012806 -0.030917 L -0.006529 -0.032822 L 0 -0.033465 L 0 -0.033465 L 0.006529 -0.032822 L 0.012806 -0.030917 L 0.018592 -0.027825 L 0.023663 -0.023663 L 0.027825 -0.018592 L 0.030917 -0.012806 L 0.032822 -0.006529 L 0.033465 0 L 0.033465 0 L 0.032822 0.006529 L 0.030917 0.012806 L 0.027825 0.018592 L 0.023663 0.023663 L 0.018592 0.027825 L 0.012806 0.030917 L 0.006529 0.032822 L 0 0.033465 L 0 0.033465 L -0.006529 0.032822 L -0.012806 0.030917 L -0.018592 0.027825 L -0.023663 0.023663 L -0.027825 0.018592 L -0.030917 0.012806 L -0.032822 0.006529 L -0.033465 0 L -0.033465 0 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.03937, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M -0.033465 0 L -0.032822 -0.006529 L -0.030917 -0.012806 L -0.027825 -0.018592 L -0.023663 -0.023663 L -0.018592 -0.027825 L -0.012806 -0.030917 L -0.006529 -0.032822 L 0 -0.033465 L 0 -0.033465 L 0.006529 -0.032822 L 0.012806 -0.030917 L 0.018592 -0.027825 L 0.023663 -0.023663 L 0.027825 -0.018592 L 0.030917 -0.012806 L 0.032822 -0.006529 L 0.033465 0 L 0.033465 0 L 0.032822 0.006529 L 0.030917 0.012806 L 0.027825 0.018592 L 0.023663 0.023663 L 0.018592 0.027825 L 0.012806 0.030917 L 0.006529 0.032822 L 0 0.033465 L 0 0.033465 L -0.006529 0.032822 L -0.012806 0.030917 L -0.018592 0.027825 L -0.023663 0.023663 L -0.027825 0.018592 L -0.030917 0.012806 L -0.032822 0.006529 L -0.033465 0 L -0.033465 0 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.03937, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** horizontal pin header SMD 2.54mm — from `PinHeader_01x03_P2.54mm_Horizontal_SMD.kicad_mod`. */
export const PinHeader_01x03_P2_54mm_Horizontal_SMD: Footprint = {
  "1": {
    shape: "M -0.049213 0.033465 L 0.049213 0.033465 L 0.049213 -0.033465 L -0.049213 -0.033465 L -0.049213 0.033465 ",
    pos: [0, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.049213 0.033465 L 0.049213 0.033465 L 0.049213 -0.033465 L -0.049213 -0.033465 L -0.049213 0.033465 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.049213 0.033465 L 0.049213 0.033465 L 0.049213 -0.033465 L -0.049213 -0.033465 L -0.049213 0.033465 ",
    pos: [0, -0.2],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** Through hole straight pin header, 2.54mm pitch, single row — from `PinHeader_01x03_P2.54mm_Vertical_THT_D1.4mm.kicad_mod`. */
export const PinHeader_01x03_P2_54mm_Vertical_THT_D1_4mm: Footprint = {
  "1": {
    shape: "M 0.041339 0 L 0.040711 0.007178 L 0.038846 0.014139 L 0.0358 0.020669 L 0.031667 0.026572 L 0.026572 0.031667 L 0.020669 0.0358 L 0.014139 0.038846 L 0.007178 0.040711 L 0 0.041339 L -0.007178 0.040711 L -0.014139 0.038846 L -0.020669 0.0358 L -0.026572 0.031667 L -0.031667 0.026572 L -0.0358 0.020669 L -0.038846 0.014139 L -0.040711 0.007178 L -0.041339 0 L -0.040711 -0.007178 L -0.038846 -0.014139 L -0.0358 -0.020669 L -0.031667 -0.026572 L -0.026572 -0.031667 L -0.020669 -0.0358 L -0.014139 -0.038846 L -0.007178 -0.040711 L 0 -0.041339 L 0.007178 -0.040711 L 0.014139 -0.038846 L 0.020669 -0.0358 L 0.026572 -0.031667 L 0.031667 -0.026572 L 0.0358 -0.020669 L 0.038846 -0.014139 L 0.040711 -0.007178 L 0.041339 0 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M 0.041339 0 L 0.040711 0.007178 L 0.038846 0.014139 L 0.0358 0.020669 L 0.031667 0.026572 L 0.026572 0.031667 L 0.020669 0.0358 L 0.014139 0.038846 L 0.007178 0.040711 L 0 0.041339 L -0.007178 0.040711 L -0.014139 0.038846 L -0.020669 0.0358 L -0.026572 0.031667 L -0.031667 0.026572 L -0.0358 0.020669 L -0.038846 0.014139 L -0.040711 0.007178 L -0.041339 0 L -0.040711 -0.007178 L -0.038846 -0.014139 L -0.0358 -0.020669 L -0.031667 -0.026572 L -0.026572 -0.031667 L -0.020669 -0.0358 L -0.014139 -0.038846 L -0.007178 -0.040711 L 0 -0.041339 L 0.007178 -0.040711 L 0.014139 -0.038846 L 0.020669 -0.0358 L 0.026572 -0.031667 L 0.031667 -0.026572 L 0.0358 -0.020669 L 0.038846 -0.014139 L 0.040711 -0.007178 L 0.041339 0 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "3": {
    shape: "M 0.041339 0 L 0.040711 0.007178 L 0.038846 0.014139 L 0.0358 0.020669 L 0.031667 0.026572 L 0.026572 0.031667 L 0.020669 0.0358 L 0.014139 0.038846 L 0.007178 0.040711 L 0 0.041339 L -0.007178 0.040711 L -0.014139 0.038846 L -0.020669 0.0358 L -0.026572 0.031667 L -0.031667 0.026572 L -0.0358 0.020669 L -0.038846 0.014139 L -0.040711 0.007178 L -0.041339 0 L -0.040711 -0.007178 L -0.038846 -0.014139 L -0.0358 -0.020669 L -0.031667 -0.026572 L -0.026572 -0.031667 L -0.020669 -0.0358 L -0.014139 -0.038846 L -0.007178 -0.040711 L 0 -0.041339 L 0.007178 -0.040711 L 0.014139 -0.038846 L 0.020669 -0.0358 L 0.026572 -0.031667 L 0.031667 -0.026572 L 0.0358 -0.020669 L 0.038846 -0.014139 L 0.040711 -0.007178 L 0.041339 0 ",
    pos: [0, -0.2],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 3,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** Through hole straight pin header, 2.54mm pitch, single row — from `PinHeader_01x03_P2.54mm_Vertical_THT_D1mm.kicad_mod`. */
export const PinHeader_01x03_P2_54mm_Vertical_THT_D1mm: Footprint = {
  "1": {
    shape: "M -0.033465 0 L -0.032822 -0.006529 L -0.030917 -0.012806 L -0.027825 -0.018592 L -0.023663 -0.023663 L -0.018592 -0.027825 L -0.012806 -0.030917 L -0.006529 -0.032822 L 0 -0.033465 L 0 -0.033465 L 0.006529 -0.032822 L 0.012806 -0.030917 L 0.018592 -0.027825 L 0.023663 -0.023663 L 0.027825 -0.018592 L 0.030917 -0.012806 L 0.032822 -0.006529 L 0.033465 0 L 0.033465 0 L 0.032822 0.006529 L 0.030917 0.012806 L 0.027825 0.018592 L 0.023663 0.023663 L 0.018592 0.027825 L 0.012806 0.030917 L 0.006529 0.032822 L 0 0.033465 L 0 0.033465 L -0.006529 0.032822 L -0.012806 0.030917 L -0.018592 0.027825 L -0.023663 0.023663 L -0.027825 0.018592 L -0.030917 0.012806 L -0.032822 0.006529 L -0.033465 0 L -0.033465 0 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.03937, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M -0.033465 0 L -0.032822 -0.006529 L -0.030917 -0.012806 L -0.027825 -0.018592 L -0.023663 -0.023663 L -0.018592 -0.027825 L -0.012806 -0.030917 L -0.006529 -0.032822 L 0 -0.033465 L 0 -0.033465 L 0.006529 -0.032822 L 0.012806 -0.030917 L 0.018592 -0.027825 L 0.023663 -0.023663 L 0.027825 -0.018592 L 0.030917 -0.012806 L 0.032822 -0.006529 L 0.033465 0 L 0.033465 0 L 0.032822 0.006529 L 0.030917 0.012806 L 0.027825 0.018592 L 0.023663 0.023663 L 0.018592 0.027825 L 0.012806 0.030917 L 0.006529 0.032822 L 0 0.033465 L 0 0.033465 L -0.006529 0.032822 L -0.012806 0.030917 L -0.018592 0.027825 L -0.023663 0.023663 L -0.027825 0.018592 L -0.030917 0.012806 L -0.032822 0.006529 L -0.033465 0 L -0.033465 0 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.03937, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "3": {
    shape: "M -0.033465 0 L -0.032822 -0.006529 L -0.030917 -0.012806 L -0.027825 -0.018592 L -0.023663 -0.023663 L -0.018592 -0.027825 L -0.012806 -0.030917 L -0.006529 -0.032822 L 0 -0.033465 L 0 -0.033465 L 0.006529 -0.032822 L 0.012806 -0.030917 L 0.018592 -0.027825 L 0.023663 -0.023663 L 0.027825 -0.018592 L 0.030917 -0.012806 L 0.032822 -0.006529 L 0.033465 0 L 0.033465 0 L 0.032822 0.006529 L 0.030917 0.012806 L 0.027825 0.018592 L 0.023663 0.023663 L 0.018592 0.027825 L 0.012806 0.030917 L 0.006529 0.032822 L 0 0.033465 L 0 0.033465 L -0.006529 0.032822 L -0.012806 0.030917 L -0.018592 0.027825 L -0.023663 0.023663 L -0.027825 0.018592 L -0.030917 0.012806 L -0.032822 0.006529 L -0.033465 0 L -0.033465 0 ",
    pos: [0, -0.2],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 3,
    drill: { diameter: 0.03937, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** Pin socket, 2.54mm pitch, horizontal, surface mount — from `PinSocket_01x02_P2.54mm_Horizontal_SMD.kicad_mod`. */
export const PinSocket_01x02_P2_54mm_Horizontal_SMD: Footprint = {
  "1": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** vertical pin socket SMD 2.54mm — from `PinSocket_01x02_P2.54mm_Vertical_SMD.kicad_mod`. */
export const PinSocket_01x02_P2_54mm_Vertical_SMD: Footprint = {
  "1": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0.064961, 0.05],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [-0.064961, -0.05],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Pin socket, 2.54mm pitch, horizontal, surface mount — from `PinSocket_01x03_P2.54mm_Horizontal_SMD.kicad_mod`. */
export const PinSocket_01x03_P2_54mm_Horizontal_SMD: Footprint = {
  "1": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0, -0.1],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0, -0.2],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** vertical pin socket SMD 2.54mm — from `PinSocket_01x03_P2.54mm_Vertical_SMD.kicad_mod`. */
export const PinSocket_01x03_P2_54mm_Vertical_SMD: Footprint = {
  "1": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0.064961, 0.1],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [-0.064961, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.03937 0.019685 L 0.03937 0.019685 L 0.03937 -0.019685 L -0.03937 -0.019685 L -0.03937 0.019685 ",
    pos: [0.064961, -0.1],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** trimmer smd — from `Potentiometer_TT_Model-23_4.5x5.0x3.0mm.kicad_mod`. */
export const Potentiometer_TT_Model_23_4_5x5_0x3_0mm: Footprint = {
  "1": {
    shape: "M -0.029528 0.03937 L 0.029528 0.03937 L 0.029528 -0.03937 L -0.029528 -0.03937 L -0.029528 0.03937 ",
    pos: [0.045669, -0.108268],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.03937 0.049213 L 0.03937 0.049213 L 0.03937 -0.049213 L -0.03937 -0.049213 L -0.03937 0.049213 ",
    pos: [0, 0.108268],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.029528 0.03937 L 0.029528 0.03937 L 0.029528 -0.03937 L -0.029528 -0.03937 L -0.029528 0.03937 ",
    pos: [-0.045276, -0.108268],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** Transistor SMD 1206, hand soldering — from `Q_1206.kicad_mod`. */
export const Q_1206: Footprint = {
  "1": {
    shape: "M -0.027559 0.033465 L 0.027559 0.033465 L 0.027559 -0.033465 L -0.027559 -0.033465 L -0.027559 0.033465 ",
    pos: [-0.066929, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.027559 0.033465 L 0.027559 0.033465 L 0.027559 -0.033465 L -0.027559 -0.033465 L -0.027559 0.033465 ",
    pos: [0.066929, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Resistor SMD 0603 — from `R_0603.kicad_mod`. */
export const R_0603: Footprint = {
  "1": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [-0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.015748 0.015748 L 0.015748 0.015748 L 0.015748 -0.015748 L -0.015748 -0.015748 L -0.015748 0.015748 ",
    pos: [0.029528, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Resistor SMD 1206, hand soldering — from `R_1206.kicad_mod`. */
export const R_1206: Footprint = {
  "1": {
    shape: "M -0.023622 0.031496 L 0.023622 0.031496 L 0.023622 -0.031496 L -0.023622 -0.031496 L -0.023622 0.031496 ",
    pos: [-0.059055, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.023622 0.031496 L 0.023622 0.031496 L 0.023622 -0.031496 L -0.023622 -0.031496 L -0.023622 0.031496 ",
    pos: [0.059055, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** Resistor SMD 2010, reflow soldering, Vishay (see dcrcw.pdf) — from `R_2010.kicad_mod`. */
export const R_2010: Footprint = {
  "1": {
    shape: "M -0.031496 0.051181 L 0.031496 0.051181 L 0.031496 -0.051181 L -0.031496 -0.051181 L -0.031496 0.051181 ",
    pos: [-0.098425, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.031496 0.051181 L 0.031496 0.051181 L 0.031496 -0.051181 L -0.031496 -0.051181 L -0.031496 0.051181 ",
    pos: [0.098425, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** SOD-123 — from `SOD-123.kicad_mod`. */
export const SOD_123: Footprint = {
  "1": {
    shape: "M -0.023622 0.015748 L 0.023622 0.015748 L 0.023622 -0.015748 L -0.023622 -0.015748 L -0.023622 0.015748 ",
    pos: [-0.070866, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.023622 0.015748 L 0.023622 0.015748 L 0.023622 -0.015748 L -0.023622 -0.015748 L -0.023622 0.015748 ",
    pos: [0.070866, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** SOT-23-3, Standard — from `SOT-23-3.kicad_mod`. */
export const SOT_23_3: Footprint = {
  "1": {
    shape: "M -0.019685 0.01378 L 0.019685 0.01378 L 0.019685 -0.01378 L -0.019685 -0.01378 L -0.019685 0.01378 ",
    pos: [-0.047244, 0.037402],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 1,
  },
  "2": {
    shape: "M -0.019685 0.01378 L 0.019685 0.01378 L 0.019685 -0.01378 L -0.019685 -0.01378 L -0.019685 0.01378 ",
    pos: [-0.047244, -0.037402],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 2,
  },
  "3": {
    shape: "M -0.019685 0.01378 L 0.019685 0.01378 L 0.019685 -0.01378 L -0.019685 -0.01378 L -0.019685 0.01378 ",
    pos: [0.047244, 0],
    layers: ["F.Cu", "F.Mask", "F.Paste"],
    index: 3,
  },
};

/** Light Touch Switch — from `Button_CnK_PTS636.0_6x3.5mm.kicad_mod`. */
export const SW_PUSH: Footprint = {
  "1": {
    shape: "M -0.049213 0.029528 L 0.049213 0.029528 L 0.049213 -0.029528 L -0.049213 -0.029528 L -0.049213 0.029528 ",
    pos: [-0.15748, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.049213 0.029528 L 0.049213 0.029528 L 0.049213 -0.029528 L -0.049213 -0.029528 L -0.049213 0.029528 ",
    pos: [0.15748, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** switch spdt right angle slide — from `Switch_Slide_RightAngle_CnK_AYZ0102AGRLC_7.2x3mm.kicad_mod`. */
export const SW_SPDT: Footprint = {
  "1": {
    shape: "M -0.019685 0.023622 L 0.019685 0.023622 L 0.019685 -0.023622 L -0.019685 -0.023622 L -0.019685 0.023622 ",
    pos: [-0.098425, 0.102362],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.019685 0.023622 L 0.019685 0.023622 L 0.019685 -0.023622 L -0.019685 -0.023622 L -0.019685 0.023622 ",
    pos: [0, 0.102362],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.019685 0.023622 L 0.019685 0.023622 L 0.019685 -0.023622 L -0.019685 -0.023622 L -0.019685 0.023622 ",
    pos: [0.098425, 0.102362],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
  "": {
    shape: "M 0 0.020669 L -0.00535 0.019965 L -0.010335 0.0179 L -0.014615 0.014615 L -0.0179 0.010335 L -0.019965 0.00535 L -0.020669 0 L -0.019965 -0.00535 L -0.0179 -0.010335 L -0.014615 -0.014615 L -0.010335 -0.0179 L -0.00535 -0.019965 L 0 -0.020669 L 0.00535 -0.019965 L 0.010335 -0.0179 L 0.014615 -0.014615 L 0.0179 -0.010335 L 0.019965 -0.00535 L 0.020669 0 L 0.019965 0.00535 L 0.0179 0.010335 L 0.014615 0.014615 L 0.010335 0.0179 L 0.00535 0.019965 L 0 0.020669 ",
    pos: [-0.059055, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 4,
    drill: { diameter: 0.033465, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "_1": {
    shape: "M 0.020669 0 L 0.019965 0.00535 L 0.0179 0.010335 L 0.014615 0.014615 L 0.010335 0.0179 L 0.00535 0.019965 L 0 0.020669 L -0.00535 0.019965 L -0.010335 0.0179 L -0.014615 0.014615 L -0.0179 0.010335 L -0.019965 0.00535 L -0.020669 0 L -0.019965 -0.00535 L -0.0179 -0.010335 L -0.014615 -0.014615 L -0.010335 -0.0179 L -0.00535 -0.019965 L 0 -0.020669 L 0.00535 -0.019965 L 0.010335 -0.0179 L 0.014615 -0.014615 L 0.0179 -0.010335 L 0.019965 -0.00535 L 0.020669 0 ",
    pos: [0.059055, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 5,
    drill: { diameter: 0.033465, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** switch slide top spdt smd — from `Switch_Slide_Top_CnK_JS102011JCQN_8.5x3.5mm.kicad_mod`. */
export const Switch_Slide_Top_CnK_JS102011JCQN_8_5x3_5mm: Footprint = {
  "1": {
    shape: "M 0.019685 0 L 0.019014 0.005095 L 0.017048 0.009843 L 0.013919 0.013919 L 0.009843 0.017048 L 0.005095 0.019014 L 0 0.019685 L -0.005095 0.019014 L -0.009843 0.017048 L -0.013919 0.013919 L -0.017048 0.009843 L -0.019014 0.005095 L -0.019685 0 L -0.019014 -0.005095 L -0.017048 -0.009843 L -0.013919 -0.013919 L -0.009843 -0.017048 L -0.005095 -0.019014 L 0 -0.019685 L 0.005095 -0.019014 L 0.009843 -0.017048 L 0.013919 -0.013919 L 0.017048 -0.009843 L 0.019014 -0.005095 L 0.019685 0 ",
    pos: [-0.098425, -0.062992],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M 0.019685 0 L 0.019014 0.005095 L 0.017048 0.009843 L 0.013919 0.013919 L 0.009843 0.017048 L 0.005095 0.019014 L 0 0.019685 L -0.005095 0.019014 L -0.009843 0.017048 L -0.013919 0.013919 L -0.017048 0.009843 L -0.019014 0.005095 L -0.019685 0 L -0.019014 -0.005095 L -0.017048 -0.009843 L -0.013919 -0.013919 L -0.009843 -0.017048 L -0.005095 -0.019014 L 0 -0.019685 L 0.005095 -0.019014 L 0.009843 -0.017048 L 0.013919 -0.013919 L 0.017048 -0.009843 L 0.019014 -0.005095 L 0.019685 0 ",
    pos: [0, 0.062992],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M 0.019685 0 L 0.019014 0.005095 L 0.017048 0.009843 L 0.013919 0.013919 L 0.009843 0.017048 L 0.005095 0.019014 L 0 0.019685 L -0.005095 0.019014 L -0.009843 0.017048 L -0.013919 0.013919 L -0.017048 0.009843 L -0.019014 0.005095 L -0.019685 0 L -0.019014 -0.005095 L -0.017048 -0.009843 L -0.013919 -0.013919 L -0.009843 -0.017048 L -0.005095 -0.019014 L 0 -0.019685 L 0.005095 -0.019014 L 0.009843 -0.017048 L 0.013919 -0.013919 L 0.017048 -0.009843 L 0.019014 -0.005095 L 0.019685 0 ",
    pos: [0.098425, -0.062992],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** switch slide top spdt smd JS102011SCQN — from `Switch_Slide_Top_CnK_JS102011SCQN_8.5x3.5mm.kicad_mod`. */
export const Switch_Slide_Top_CnK_JS102011SCQN_8_5x3_5mm: Footprint = {
  "1": {
    shape: "M -0.019685 0.049213 L 0.019685 0.049213 L 0.019685 -0.049213 L -0.019685 -0.049213 L -0.019685 0.049213 ",
    pos: [-0.098425, -0.108268],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.019685 0.049213 L 0.019685 0.049213 L 0.019685 -0.049213 L -0.019685 -0.049213 L -0.019685 0.049213 ",
    pos: [0, 0.108268],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.019685 0.049213 L 0.019685 0.049213 L 0.019685 -0.049213 L -0.019685 -0.049213 L -0.019685 0.049213 ",
    pos: [0.098425, -0.108268],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** TO-252 Package — from `TO-252.kicad_mod`. */
export const TO_252: Footprint = {
  "1": {
    shape: "M -0.059055 0.029528 L 0.059055 0.029528 L 0.059055 -0.029528 L -0.059055 -0.029528 L -0.059055 0.029528 ",
    pos: [-0.165354, 0.089764],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "2": {
    shape: "M -0.129921 0.11811 L 0.129921 0.11811 L 0.129921 -0.11811 L -0.129921 -0.11811 L -0.129921 0.11811 ",
    pos: [0.086614, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
  "3": {
    shape: "M -0.059055 0.029528 L 0.059055 0.029528 L 0.059055 -0.029528 L -0.059055 -0.029528 L -0.059055 0.029528 ",
    pos: [-0.165354, -0.089764],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 3,
  },
};

/** TERM BLOCK 1POS SIDE ENTRY SMD — from `TerminalBlock_1pos_Metz_SM99S01VBNN05G7.kicad_mod`. */
export const TerminalBlock_1pos_Metz_SM99S01VBNN05G7: Footprint = {
  "1": {
    shape: "M -0.114173 0.03937 L 0.114173 0.03937 L 0.114173 -0.03937 L -0.114173 -0.03937 L -0.114173 0.03937 ",
    pos: [-0.167323, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 1,
  },
  "1_1": {
    shape: "M -0.084646 0.03937 L 0.084646 0.03937 L 0.084646 -0.03937 L -0.084646 -0.03937 L -0.084646 0.03937 ",
    pos: [0.137795, 0],
    layers: ["F.Cu", "F.Paste", "F.Mask"],
    index: 2,
  },
};

/** 2 Position Wire to Board Terminal Block Horizontal with Board 0.138" (3.50mm) Through Hole — from `TerminalBlock_OnShore_1x02_P3.50mm_Horizontal.kicad_mod`. */
export const TerminalBlock_OnShore_1x02_P3_50mm_Horizontal: Footprint = {
  "1": {
    shape: "M -0.059055 0.059055 L 0.059055 0.059055 L 0.059055 -0.059055 L -0.059055 -0.059055 L -0.059055 0.059055 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M 0.059055 0 L 0.058328 0.009238 L 0.056165 0.018249 L 0.052618 0.02681 L 0.047777 0.034712 L 0.041758 0.041758 L 0.034712 0.047777 L 0.02681 0.052618 L 0.018249 0.056165 L 0.009238 0.058328 L 0 0.059055 L -0.009238 0.058328 L -0.018249 0.056165 L -0.02681 0.052618 L -0.034712 0.047777 L -0.041758 0.041758 L -0.047777 0.034712 L -0.052618 0.02681 L -0.056165 0.018249 L -0.058328 0.009238 L -0.059055 0 L -0.058328 -0.009238 L -0.056165 -0.018249 L -0.052618 -0.02681 L -0.047777 -0.034712 L -0.041758 -0.041758 L -0.034712 -0.047777 L -0.02681 -0.052618 L -0.018249 -0.056165 L -0.009238 -0.058328 L 0 -0.059055 L 0.009238 -0.058328 L 0.018249 -0.056165 L 0.02681 -0.052618 L 0.034712 -0.047777 L 0.041758 -0.041758 L 0.047777 -0.034712 L 0.052618 -0.02681 L 0.056165 -0.018249 L 0.058328 -0.009238 L 0.059055 0 ",
    pos: [0.137795, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** 2 Position Wire to Board Terminal Block Horizontal with Board 0.197" (5.00mm) Through Hole — from `TerminalBlock_OnShore_1x02_P5.00mm_Horizontal.kicad_mod`. */
export const TerminalBlock_OnShore_1x02_P5_00mm_Horizontal: Footprint = {
  "1": {
    shape: "M -0.059055 0.059055 L 0.059055 0.059055 L 0.059055 -0.059055 L -0.059055 -0.059055 L -0.059055 0.059055 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M 0.059055 0 L 0.058328 0.009238 L 0.056165 0.018249 L 0.052618 0.02681 L 0.047777 0.034712 L 0.041758 0.041758 L 0.034712 0.047777 L 0.02681 0.052618 L 0.018249 0.056165 L 0.009238 0.058328 L 0 0.059055 L -0.009238 0.058328 L -0.018249 0.056165 L -0.02681 0.052618 L -0.034712 0.047777 L -0.041758 0.041758 L -0.047777 0.034712 L -0.052618 0.02681 L -0.056165 0.018249 L -0.058328 0.009238 L -0.059055 0 L -0.058328 -0.009238 L -0.056165 -0.018249 L -0.052618 -0.02681 L -0.047777 -0.034712 L -0.041758 -0.041758 L -0.034712 -0.047777 L -0.02681 -0.052618 L -0.018249 -0.056165 L -0.009238 -0.058328 L 0 -0.059055 L 0.009238 -0.058328 L 0.018249 -0.056165 L 0.02681 -0.052618 L 0.034712 -0.047777 L 0.041758 -0.041758 L 0.047777 -0.034712 L 0.052618 -0.02681 L 0.056165 -0.018249 L 0.058328 -0.009238 L 0.059055 0 ",
    pos: [0.19685, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** 3 Position Wire to Board Terminal Block Horizontal with Board 0.138" (3.50mm) Through Hole — from `TerminalBlock_OnShore_1x03_P3.50mm_Horizontal.kicad_mod`. */
export const TerminalBlock_OnShore_1x03_P3_50mm_Horizontal: Footprint = {
  "1": {
    shape: "M -0.059055 -0.059055 L -0.059055 0.059055 L 0.059055 0.059055 L 0.059055 -0.059055 L -0.059055 -0.059055 ",
    pos: [0, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 1,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "2": {
    shape: "M 0.059055 0 L 0.058328 0.009238 L 0.056165 0.018249 L 0.052618 0.02681 L 0.047777 0.034712 L 0.041758 0.041758 L 0.034712 0.047777 L 0.02681 0.052618 L 0.018249 0.056165 L 0.009238 0.058328 L 0 0.059055 L -0.009238 0.058328 L -0.018249 0.056165 L -0.02681 0.052618 L -0.034712 0.047777 L -0.041758 0.041758 L -0.047777 0.034712 L -0.052618 0.02681 L -0.056165 0.018249 L -0.058328 0.009238 L -0.059055 0 L -0.058328 -0.009238 L -0.056165 -0.018249 L -0.052618 -0.02681 L -0.047777 -0.034712 L -0.041758 -0.041758 L -0.034712 -0.047777 L -0.02681 -0.052618 L -0.018249 -0.056165 L -0.009238 -0.058328 L 0 -0.059055 L 0.009238 -0.058328 L 0.018249 -0.056165 L 0.02681 -0.052618 L 0.034712 -0.047777 L 0.041758 -0.041758 L 0.047777 -0.034712 L 0.052618 -0.02681 L 0.056165 -0.018249 L 0.058328 -0.009238 L 0.059055 0 ",
    pos: [0.137795, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 2,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
  "3": {
    shape: "M 0.059055 0 L 0.058328 0.009238 L 0.056165 0.018249 L 0.052618 0.02681 L 0.047777 0.034712 L 0.041758 0.041758 L 0.034712 0.047777 L 0.02681 0.052618 L 0.018249 0.056165 L 0.009238 0.058328 L 0 0.059055 L -0.009238 0.058328 L -0.018249 0.056165 L -0.02681 0.052618 L -0.034712 0.047777 L -0.041758 0.041758 L -0.047777 0.034712 L -0.052618 0.02681 L -0.056165 0.018249 L -0.058328 0.009238 L -0.059055 0 L -0.058328 -0.009238 L -0.056165 -0.018249 L -0.052618 -0.02681 L -0.047777 -0.034712 L -0.041758 -0.041758 L -0.034712 -0.047777 L -0.02681 -0.052618 L -0.018249 -0.056165 L -0.009238 -0.058328 L 0 -0.059055 L 0.009238 -0.058328 L 0.018249 -0.056165 L 0.02681 -0.052618 L 0.034712 -0.047777 L 0.041758 -0.041758 L 0.047777 -0.034712 L 0.052618 -0.02681 L 0.056165 -0.018249 L 0.058328 -0.009238 L 0.059055 0 ",
    pos: [0.275591, 0],
    layers: ["F.Cu", "B.Cu", "F.Mask", "B.Mask"],
    index: 3,
    drill: { diameter: 0.055118, start: "F.Cu", end: "B.Cu", plated: true },
  },
};

/** Every part a rail can take, by id. Whether it can is `placement()`'s to say, not this list's. */
export const COMPONENTS: Component[] = [
  { id: "BAT_COIN_20", note: "Battery-Holder Coin-Cell CR2032 Linx BAT-HLD-001", footprint: BAT_COIN_20 },
  { id: "BatteryContact_Keystone_555", note: "BatteryContact Keystone 555", footprint: BatteryContact_Keystone_555 },
  { id: "CP_Elec_100uF_Panasonic_EEE_FN1E101UL", note: "SMD capacitor, aluminum electrolytic, Nichicon, 10.0x10.0mm", footprint: CP_Elec_100uF_Panasonic_EEE_FN1E101UL },
  { id: "CP_Elec_10F_Tecate_TPLC_3R8", note: "CAP LITH HYBRID 10F 3.8V T/H", footprint: CP_Elec_10F_Tecate_TPLC_3R8 },
  { id: "CP_Elec_47uF_Panasonic_EEE_FN1H470XL", note: "CP Elec 47uF Panasonic EEE-FN1H470XL", footprint: CP_Elec_47uF_Panasonic_EEE_FN1H470XL },
  { id: "C_0603", note: "Capacitor SMD 0603", footprint: C_0603 },
  { id: "C_1206", note: "Capacitor SMD 1206, hand soldering", footprint: C_1206 },
  { id: "Crystal_NX5032GA_20", note: "20MHz ±50ppm Crystal 8pF 70 Ohms 2-SMD, No Lead", footprint: Crystal_NX5032GA_20 },
  { id: "Diode_Schottky_0603", note: "Diode Schottky 0603", footprint: Diode_Schottky_0603 },
  { id: "Diode_Schottky_MiniSMA", note: "Mini-SMA Schottky diode footprint", footprint: Diode_Schottky_MiniSMA },
  { id: "Diode_Schottky_SOD123", note: "SOD-123 footprint for the Schottky diode", footprint: Diode_Schottky_SOD123 },
  { id: "ECS_CR2_20", note: "SMD Resomator/Filter Murata SFECV, 6.9x2.9mm^2 package", footprint: ECS_CR2_20 },
  { id: "Header_JST_PH_1x02_P2mm_Vertical_SMD", note: "Header JST PH 1x02 P2mm Vertical SMD", footprint: Header_JST_PH_1x02_P2mm_Vertical_SMD },
  { id: "Header_JST_PH_1x03_P2mm_Vertical_SMD", note: "Header JST PH 1x03 P2mm Vertical SMD", footprint: Header_JST_PH_1x03_P2mm_Vertical_SMD },
  { id: "Jumper_1206", note: "Jumper, based on SMD 1206 resistor", footprint: Jumper_1206 },
  { id: "LED_0603", note: "LED SMD 0603, hand soldering", footprint: LED_0603 },
  { id: "LED_1206", note: "LED SMD 1206, hand soldering", footprint: LED_1206 },
  { id: "LED_Luminus_1206", note: "LED Luminus 1206", footprint: LED_Luminus_1206 },
  { id: "L_1210", note: "Inductor SMD 1210, hand soldering", footprint: L_1210 },
  { id: "PinHeader_01x02_P2_54mm_Horizontal_SMD", note: "horizontal pin header SMD 2.54mm", footprint: PinHeader_01x02_P2_54mm_Horizontal_SMD },
  { id: "PinHeader_01x02_P2_54mm_Vertical_THT_D1_4mm", note: "Through hole straight pin header, 2.54mm pitch, single row", footprint: PinHeader_01x02_P2_54mm_Vertical_THT_D1_4mm },
  { id: "PinHeader_01x02_P2_54mm_Vertical_THT_D1mm", note: "Through hole straight pin header, 2.54mm pitch, single row", footprint: PinHeader_01x02_P2_54mm_Vertical_THT_D1mm },
  { id: "PinHeader_01x03_P2_54mm_Horizontal_SMD", note: "horizontal pin header SMD 2.54mm", footprint: PinHeader_01x03_P2_54mm_Horizontal_SMD },
  { id: "PinHeader_01x03_P2_54mm_Vertical_THT_D1_4mm", note: "Through hole straight pin header, 2.54mm pitch, single row", footprint: PinHeader_01x03_P2_54mm_Vertical_THT_D1_4mm },
  { id: "PinHeader_01x03_P2_54mm_Vertical_THT_D1mm", note: "Through hole straight pin header, 2.54mm pitch, single row", footprint: PinHeader_01x03_P2_54mm_Vertical_THT_D1mm },
  { id: "PinSocket_01x02_P2_54mm_Horizontal_SMD", note: "Pin socket, 2.54mm pitch, horizontal, surface mount", footprint: PinSocket_01x02_P2_54mm_Horizontal_SMD },
  { id: "PinSocket_01x02_P2_54mm_Vertical_SMD", note: "vertical pin socket SMD 2.54mm", footprint: PinSocket_01x02_P2_54mm_Vertical_SMD },
  { id: "PinSocket_01x03_P2_54mm_Horizontal_SMD", note: "Pin socket, 2.54mm pitch, horizontal, surface mount", footprint: PinSocket_01x03_P2_54mm_Horizontal_SMD },
  { id: "PinSocket_01x03_P2_54mm_Vertical_SMD", note: "vertical pin socket SMD 2.54mm", footprint: PinSocket_01x03_P2_54mm_Vertical_SMD },
  { id: "Potentiometer_TT_Model_23_4_5x5_0x3_0mm", note: "trimmer smd", footprint: Potentiometer_TT_Model_23_4_5x5_0x3_0mm },
  { id: "Q_1206", note: "Transistor SMD 1206, hand soldering", footprint: Q_1206 },
  { id: "R_0603", note: "Resistor SMD 0603", footprint: R_0603 },
  { id: "R_1206", note: "Resistor SMD 1206, hand soldering", footprint: R_1206 },
  { id: "R_2010", note: "Resistor SMD 2010, reflow soldering, Vishay (see dcrcw.pdf)", footprint: R_2010 },
  { id: "SOD_123", note: "SOD-123", footprint: SOD_123 },
  { id: "SOT_23_3", note: "SOT-23-3, Standard", footprint: SOT_23_3 },
  { id: "SW_PUSH", note: "Light Touch Switch", footprint: SW_PUSH },
  { id: "SW_SPDT", note: "switch spdt right angle slide", footprint: SW_SPDT },
  { id: "Switch_Slide_Top_CnK_JS102011JCQN_8_5x3_5mm", note: "switch slide top spdt smd", footprint: Switch_Slide_Top_CnK_JS102011JCQN_8_5x3_5mm },
  { id: "Switch_Slide_Top_CnK_JS102011SCQN_8_5x3_5mm", note: "switch slide top spdt smd JS102011SCQN", footprint: Switch_Slide_Top_CnK_JS102011SCQN_8_5x3_5mm },
  { id: "TO_252", note: "TO-252 Package", footprint: TO_252 },
  { id: "TerminalBlock_1pos_Metz_SM99S01VBNN05G7", note: "TERM BLOCK 1POS SIDE ENTRY SMD", footprint: TerminalBlock_1pos_Metz_SM99S01VBNN05G7 },
  { id: "TerminalBlock_OnShore_1x02_P3_50mm_Horizontal", note: "2 Position Wire to Board Terminal Block Horizontal with Board 0.138\" (3.50mm) Through Hole", footprint: TerminalBlock_OnShore_1x02_P3_50mm_Horizontal },
  { id: "TerminalBlock_OnShore_1x02_P5_00mm_Horizontal", note: "2 Position Wire to Board Terminal Block Horizontal with Board 0.197\" (5.00mm) Through Hole", footprint: TerminalBlock_OnShore_1x02_P5_00mm_Horizontal },
  { id: "TerminalBlock_OnShore_1x03_P3_50mm_Horizontal", note: "3 Position Wire to Board Terminal Block Horizontal with Board 0.138\" (3.50mm) Through Hole", footprint: TerminalBlock_OnShore_1x03_P3_50mm_Horizontal },
];
