// GENERATED by `ocaml/footprints.ml` — do not edit by hand; run `npm run footprints`.
//
// Footprints from fab-modules `pcb.py`, in millimetres. Every value is that library's own, converted
// from the inches it is authored in: a named part is the size it is, and inventing a footprint shows
// one that does not exist.

/** A part's copper: pads, and any holes it is mounted through. Millimetres, origin at the part. */
export interface Footprint {
  name: string;
  source: string;
  pads: { cx: number; cy: number; w: number; h: number; label: string }[];
  holes: { cx: number; cy: number; r: number }[];
}

/** pcb.py class LED_1206 - 1206 LED. Generated — see `ocaml/footprints.ml`. */
export const LED_1206: Footprint = {
  name: "LED_1206",
  source: "pcb.py class LED_1206 - 1206 LED",
  pads: [
    { cx: -1.3970, cy: 0.0000, w: 1.6256, h: 1.7272, label: "A" },
    { cx: 1.3970, cy: 0.0000, w: 1.6256, h: 1.7272, label: "C" },
  ],
  holes: [
  ],
};

/** pcb.py class R_1206 - 1206 resistor. Generated — see `ocaml/footprints.ml`. */
export const R_1206: Footprint = {
  name: "R_1206",
  source: "pcb.py class R_1206 - 1206 resistor",
  pads: [
    { cx: -1.5240, cy: 0.0000, w: 1.6256, h: 1.7272, label: "" },
    { cx: 1.5240, cy: 0.0000, w: 1.6256, h: 1.7272, label: "" },
  ],
  holes: [
  ],
};

/** pcb.py class slide_switch - C&K AYZ0102AGRLC (common moved to the far edge). Generated — see `ocaml/footprints.ml`. */
export const slide_switch: Footprint = {
  name: "slide_switch",
  source: "pcb.py class slide_switch - C&K AYZ0102AGRLC (common moved to the far edge)",
  pads: [
    { cx: -2.4892, cy: 2.5400, w: 0.9906, h: 1.1938, label: "1" },
    { cx: 0.0000, cy: -2.5400, w: 0.9906, h: 1.1938, label: "2 common" },
    { cx: 2.4892, cy: 2.5400, w: 0.9906, h: 1.1938, label: "3" },
  ],
  holes: [
    { cx: -1.4986, cy: 0.0000, r: 0.4318 },
    { cx: 1.4986, cy: 0.0000, r: 0.4318 },
  ],
};
