(* Footprints, from Neil Gershenfeld's fab-modules [pcb.py].
 *
 * That library is the authority here: its part classes carry the pad sizes and spacings that have actually
 * been cut and stuffed. Each part below quotes the class it came from and keeps the original inches beside
 * the millimetres, so a value can be checked against the source without converting anything by hand.
 *
 * This is a generator, not a runtime. It prints a TypeScript module the app imports, so the numbers live in
 * one place and cross into the app as data. The app's own hot path stays in TypeScript, where it measured
 * faster than either OCaml route to the browser. *)

let mm_of_inch inches = inches *. 25.4

type pad = {
  cx : float;      (* centre, inches *)
  cy : float;
  w : float;       (* size, inches *)
  h : float;
  label : string;  (* 'A'/'C' on an LED, empty where the part does not mark its pads *)
}

type hole = { hx : float; hy : float; hr : float }

type part = {
  name : string;
  source : string; (* the pcb.py class, and the manufacturer's part where it names one *)
  pads : pad list;
  holes : hole list;
}

(* [pad_1206 = cube(-.032,.032,-.034,.034,0,0)] *)
let pad_1206 = (0.064, 0.068)

let led_1206 =
  (* class LED_1206: shape at ∓.06, pads at ∓.055, labelled A and C *)
  let w, h = pad_1206 in
  {
    name = "LED_1206";
    source = "pcb.py class LED_1206 - 1206 LED";
    pads =
      [
        { cx = -0.055; cy = 0.0; w; h; label = "A" };
        { cx = 0.055; cy = 0.0; w; h; label = "C" };
      ];
    holes = [];
  }

let r_1206 =
  (* class R_1206: two pads at ±.06, unlabelled *)
  let w, h = pad_1206 in
  {
    name = "R_1206";
    source = "pcb.py class R_1206 - 1206 resistor";
    pads =
      [ { cx = -0.06; cy = 0.0; w; h; label = "" }; { cx = 0.06; cy = 0.0; w; h; label = "" } ];
    holes = [];
  }

let slide_switch =
  (* class slide_switch: pads .039 x .047 at x = -.098, 0, .098 and y = .1;
     holes .034 across at x = ±.118/2, y = 0 *)
  {
    name = "slide_switch";
    source = "pcb.py class slide_switch - C&K AYZ0102AGRLC";
    pads =
      [
        { cx = -0.098; cy = 0.1; w = 0.039; h = 0.047; label = "1" };
        { cx = 0.0; cy = 0.1; w = 0.039; h = 0.047; label = "2" };
        { cx = 0.098; cy = 0.1; w = 0.039; h = 0.047; label = "3" };
      ];
    holes = [ { hx = -0.118 /. 2.0; hy = 0.0; hr = 0.034 /. 2.0 }; { hx = 0.118 /. 2.0; hy = 0.0; hr = 0.034 /. 2.0 } ];
  }

let parts = [ led_1206; r_1206; slide_switch ]

let f v = Printf.sprintf "%.4f" (mm_of_inch v)

let emit_pad p =
  Printf.sprintf
    "    { cx: %s, cy: %s, w: %s, h: %s, label: %S },"
    (f p.cx) (f p.cy) (f p.w) (f p.h) p.label

let emit_hole h = Printf.sprintf "    { cx: %s, cy: %s, r: %s }," (f h.hx) (f h.hy) (f h.hr)

let emit p =
  Printf.printf "\n/** %s. Generated — see `ocaml/footprints.ml`. */\n" p.source;
  Printf.printf "export const %s: Footprint = {\n" p.name;
  Printf.printf "  name: %S,\n  source: %S,\n" p.name p.source;
  Printf.printf "  pads: [\n";
  List.iter (fun pd -> print_endline (emit_pad pd)) p.pads;
  Printf.printf "  ],\n  holes: [\n";
  List.iter (fun h -> print_endline (emit_hole h)) p.holes;
  Printf.printf "  ],\n};\n"

let () =
  print_string
    "// GENERATED by `ocaml/footprints.ml` — do not edit by hand; run `npm run footprints`.\n\
     //\n\
     // Footprints from fab-modules `pcb.py`, in millimetres. Every value is that library's own, converted\n\
     // from the inches it is authored in: a named part is the size it is, and inventing a footprint shows\n\
     // one that does not exist.\n\n\
     /** A part's copper: pads, and any holes it is mounted through. Millimetres, origin at the part. */\n\
     export interface Footprint {\n\
    \  name: string;\n\
    \  source: string;\n\
    \  pads: { cx: number; cy: number; w: number; h: number; label: string }[];\n\
    \  holes: { cx: number; cy: number; r: number }[];\n\
     }\n";
  List.iter emit parts
