(** Generates [src/model/footprints.generated.ts] from the vendored KiCad footprints.

    The component library is not written by hand. Pad sizes and pitches are the part's, taken from its
    manufacturer's own footprint file, so a number in the app is a number from a datasheet rather than
    one somebody measured off a drawing. Twice already a switch pitch was wrong here — 2.54mm assumed
    from a package name, then 2.5mm read off a datasheet page — and both times the file said 2.5mm
    exactly. Reading the file is the fix.

    Run with [npm run footprints]. The output is committed so the app builds without OCaml. *)

type entry = { file : string; id : string; note : string }

let library =
  [ { file = "LED_1206.kicad_mod"; id = "LED_1206"; note = "1206 chip LED" };
    { file = "R_1206.kicad_mod"; id = "R_1206"; note = "1206 chip resistor" };
    { file = "R_2010.kicad_mod"; id = "R_2010"; note = "2010 chip resistor" };
    { file = "C_1206.kicad_mod"; id = "C_1206"; note = "1206 chip capacitor" };
    { file = "Switch_SPDT_AYZ0102.kicad_mod"; id = "SW_SPDT"; note = "SPDT slide switch, 2.5mm pitch" };
    { file = "Button_PTS636.kicad_mod"; id = "SW_PUSH"; note = "6x3.5mm tactile push button" };
    { file = "Coin_Battery_20mm.kicad_mod"; id = "BAT_COIN_20"; note = "20mm coin cell holder" } ]

let dir = "../footprints/"

let quote s = "\"" ^ String.concat "\\\"" (String.split_on_char '"' s) ^ "\""

let emit_pad (name, (p : Kicad.pad)) =
  let x, y = p.pos in
  Printf.printf "  %s: {\n" (quote name);
  Printf.printf "    shape: %s,\n" (quote p.shape);
  Printf.printf "    pos: [%s, %s],\n" (Kicad.fmt x) (Kicad.fmt y);
  Printf.printf "    layers: [%s],\n" (String.concat ", " (List.map quote p.layers));
  Printf.printf "    index: %d,\n" p.index;
  (match p.drill with
   | Some d ->
       Printf.printf "    drill: { diameter: %s, start: %s, end: %s, plated: %b },\n"
         (Kicad.fmt d.diameter) (quote d.start_layer) (quote d.end_layer) d.plated
   | None -> ());
  print_string "  },\n"

let emit_component e =
  let fp = Kicad.of_file (dir ^ e.file) in
  Printf.printf "\n/** %s — from `%s`. */\n" e.note e.file;
  Printf.printf "export const %s: Footprint = {\n" e.id;
  List.iter emit_pad fp;
  print_string "};\n"

let emit_header () =
  print_string
    {|/**
 * **Model** — the component library.
 *
 * GENERATED by `npm run footprints` from the KiCad footprints in `footprints/`. Do not edit: change
 * the .kicad_mod file or `ocaml/footprints.ml` and regenerate.
 *
 * A footprint is its pads, keyed by the pad name the part's own datasheet uses. Each pad carries its
 * outline as an SVG path about its own origin, where that origin sits in the part, which layers it
 * belongs to, and a drill if it is a hole. Coordinates are inches with y up — see `ocaml/kicad.ml`
 * for why, and `footprint.ts` for the helpers that read them.
 */

/** A hole through the board, as opposed to a pad on it. */
export interface Drill {
  diameter: number;
  start: string;
  end: string;
  plated: boolean;
}

/** One terminal — or, with no copper layer, one mechanical hole. */
export interface Pad {
  /** The outline as an SVG path, inches, about this pad's own origin. */
  shape: string;
  /** Where that origin sits in the footprint, inches, y up. */
  pos: [number, number];
  layers: string[];
  /** The part's own pad number, 1-based. */
  index: number;
  drill?: Drill;
}

/** A part, as its pads. */
export type Footprint = Record<string, Pad>;

/** A library entry: the footprint plus what to call it. */
export interface Component {
  id: string;
  note: string;
  footprint: Footprint;
}
|}

let emit_catalogue () =
  print_string "\n/** Every part in the library, in the order the palette offers them. */\n";
  print_string "export const COMPONENTS: Component[] = [\n";
  List.iter
    (fun e ->
      Printf.printf "  { id: %s, note: %s, footprint: %s },\n" (quote e.id) (quote e.note) e.id)
    library;
  print_string "];\n"

let () =
  emit_header ();
  List.iter emit_component library;
  emit_catalogue ()
